# CMake generated Testfile for 
# Source directory: /home/david/proj/fluidsynth/test
# Build directory: /home/david/proj/fluidsynth/doc/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_synth_reset_cc "/home/david/proj/fluidsynth/doc/test/test_synth_reset_cc")
set_tests_properties(test_synth_reset_cc PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;10;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_sample_cache "/home/david/proj/fluidsynth/doc/test/test_sample_cache")
set_tests_properties(test_sample_cache PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;11;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_sfont_loading "/home/david/proj/fluidsynth/doc/test/test_sfont_loading")
set_tests_properties(test_sfont_loading PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;12;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_sample_rate_change "/home/david/proj/fluidsynth/doc/test/test_sample_rate_change")
set_tests_properties(test_sample_rate_change PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;13;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_preset_sample_loading "/home/david/proj/fluidsynth/doc/test/test_preset_sample_loading")
set_tests_properties(test_preset_sample_loading PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;14;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_preset_pinning "/home/david/proj/fluidsynth/doc/test/test_preset_pinning")
set_tests_properties(test_preset_pinning PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;15;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_bug_635 "/home/david/proj/fluidsynth/doc/test/test_bug_635")
set_tests_properties(test_bug_635 PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;16;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_settings_unregister_callback "/home/david/proj/fluidsynth/doc/test/test_settings_unregister_callback")
set_tests_properties(test_settings_unregister_callback PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;17;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_pointer_alignment "/home/david/proj/fluidsynth/doc/test/test_pointer_alignment")
set_tests_properties(test_pointer_alignment PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;18;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_seqbind_unregister "/home/david/proj/fluidsynth/doc/test/test_seqbind_unregister")
set_tests_properties(test_seqbind_unregister PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;19;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_synth_chorus_reverb "/home/david/proj/fluidsynth/doc/test/test_synth_chorus_reverb")
set_tests_properties(test_synth_chorus_reverb PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;20;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_snprintf "/home/david/proj/fluidsynth/doc/test/test_snprintf")
set_tests_properties(test_snprintf PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;21;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_synth_process "/home/david/proj/fluidsynth/doc/test/test_synth_process")
set_tests_properties(test_synth_process PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;22;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_ct2hz "/home/david/proj/fluidsynth/doc/test/test_ct2hz")
set_tests_properties(test_ct2hz PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;23;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_sample_validate "/home/david/proj/fluidsynth/doc/test/test_sample_validate")
set_tests_properties(test_sample_validate PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;24;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_sfont_unloading "/home/david/proj/fluidsynth/doc/test/test_sfont_unloading")
set_tests_properties(test_sfont_unloading PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;25;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_sfont_zone "/home/david/proj/fluidsynth/doc/test/test_sfont_zone")
set_tests_properties(test_sfont_zone PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;26;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_seq_event_queue_sort "/home/david/proj/fluidsynth/doc/test/test_seq_event_queue_sort")
set_tests_properties(test_seq_event_queue_sort PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;27;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_seq_scale "/home/david/proj/fluidsynth/doc/test/test_seq_scale")
set_tests_properties(test_seq_scale PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;28;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_seq_evt_order "/home/david/proj/fluidsynth/doc/test/test_seq_evt_order")
set_tests_properties(test_seq_evt_order PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;29;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_seq_event_queue_remove "/home/david/proj/fluidsynth/doc/test/test_seq_event_queue_remove")
set_tests_properties(test_seq_event_queue_remove PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;30;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_jack_obtaining_synth "/home/david/proj/fluidsynth/doc/test/test_jack_obtaining_synth")
set_tests_properties(test_jack_obtaining_synth PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;31;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(test_utf8_open "/home/david/proj/fluidsynth/doc/test/test_utf8_open")
set_tests_properties(test_utf8_open PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;23;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;32;ADD_FLUID_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
add_test(VintageDreamsWaves-v2.sf2_dump_test "/usr/bin/cmake" "-Dtest_cmd=/home/david/proj/fluidsynth/doc/test/utils/dump_sfont" "-Dtest_args=/home/david/proj/fluidsynth/sf2/VintageDreamsWaves-v2.sf2 VintageDreamsWaves-v2.sf2.yml" "-Dtest_output=VintageDreamsWaves-v2.sf2.yml" "-Dexpected_output=/home/david/proj/fluidsynth/sf2/VintageDreamsWaves-v2.sf2.yml" "-P" "/home/david/proj/fluidsynth/cmake_admin/RunOutputTest.cmake")
set_tests_properties(VintageDreamsWaves-v2.sf2_dump_test PROPERTIES  _BACKTRACE_TRIPLES "/home/david/proj/fluidsynth/cmake_admin/FluidUnitTest.cmake;66;ADD_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;36;ADD_FLUID_SF_DUMP_TEST;/home/david/proj/fluidsynth/test/CMakeLists.txt;0;")
